### ISSUE TITLE
Split betwen Rail/other and bus data via martin function

### ISSUE THREAD

**Issue by kylerchin** [CatenaryMaps/documentation#18]

**Comment by kylerchin** [comment]
![Image](https://github.com/CatenaryMaps/documentation/assets/7539174/2fdb40f6-f852-4df2-884e-c91f668f2a2b)

App barely loads Western europe on desktop, crashes on mobile

**Comment by kylerchin** [comment]
Solution is to block rendering of buses at low zoom levels

**Comment by kylerchin** [comment]
Asking for help, major bug 


![Image](https://github.com/CatenaryMaps/documentation/assets/7539174/3f479068-a468-4683-87b1-06834beab136)

**Comment by kylerchin** [comment]
https://github.com/CatenaryMaps/catenary-frontend/pull/15

**Comment by jktrn** [comment]
Resolved.
