### ISSUE TITLE
LIRR and MNR feed translation Buffer Underflow Bug

### ISSUE THREAD

**Issue by kylerchin** [CatenaryMaps/documentation#23]

**Comment by kylerchin** [comment]
```https://kactus.catenarymaps.org/gtfsrtasjson/?feed=f-mta~nyc~rt~lirr&suicidebutton=true&category=vehicles&raw=true```

Returns

```
DecodeError {
    description: "buffer underflow",
    stack: [
        (
            "FeedMessage",
            "header",
        ),
    ],
}
```

**Comment by kylerchin** [comment]
Fixed in https://github.com/CatenaryMaps/kactus-gtfs-rt/commit/5365f5c5fb7fd1e06009f8163c5e7e9203991d4b

**Comment by kylerchin** [comment]
Goofiest typo ever lol

**Comment by jktrn** [comment]
Resolved.
